In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118


Looking in indexes: https://download.pytorch.org/whl/cu118


In [3]:
!git clone https://github.com/ultralytics/yolov5

fatal: destination path 'yolov5' already exists and is not an empty directory.


In [ ]:
!cd yolov5 & pip install -r requirements.txt

In [2]:
import torch
from matplotlib import pyplot as plt
import numpy as np
import cv2

In [3]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

Using cache found in C:\Users\micha/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2024-1-7 Python-3.11.7 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape... 


In [ ]:
model

In [ ]:
img = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Cars_in_traffic_in_Auckland%2C_New_Zealand_-_copyright-free_photo_released_to_public_domain.jpg/800px-Cars_in_traffic_in_Auckland%2C_New_Zealand_-_copyright-free_photo_released_to_public_domain.jpg'


In [ ]:
results = model(img)
results.print()

In [ ]:
%matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()

In [ ]:
results.render()

In [ ]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Make detections 
    results = model(frame)
    
    cv2.imshow('YOLO', np.squeeze(results.render()))
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [2]:
import uuid   # Unique identifier
import os
import time

In [15]:
IMAGES_PATH = os.path.join('data', 'image') #/data/images
labels = ['awake', 'drowsy']
number_imgs = 10

In [16]:
cap = cv2.VideoCapture(0)
# Loop through labels
for label in labels:
    print('Collecting images for {}'.format(label))
    time.sleep(5)
    
    # Loop through image range
    for img_num in range(number_imgs):
        print('Collecting images for {}, image number {}'.format(label, img_num))
        
        # Webcam feed
        ret, frame = cap.read()
        
        # Naming out image path
        imgname = os.path.join(IMAGES_PATH, label+'.'+str(uuid.uuid1())+'.jpg')
        
        # Writes out image to file 
        cv2.imwrite(imgname, frame)
        
        # Render to the screen
        cv2.imshow('Image Collection', frame)
        
        # 2 second delay between captures
        time.sleep(2)
        
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

In [17]:
print(os.path.join(IMAGES_PATH, labels[0]+'.'+str(uuid.uuid1())+'.jpg'))

data\image\awake.6dfc8a3b-9e93-11ee-ba24-e00af687c89b.jpg


In [ ]:
for label in labels:
    print('Collecting images for {}'.format(label))
    for img_num in range(number_imgs):
        print('Collecting images for {}, image number {}'.format(label, img_num))
        imgname = os.path.join(IMAGES_PATH, label+'.'+str(uuid.uuid1())+'.jpg')
        print(imgname)   

In [ ]:
!git clone https://github.com/tzutalin/labelImg

In [2]:
%pip install pyqt5 lxml --upgrade
!cd labelImg && pyrcc5 -o libs/resources.py resources.qrc

  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/2e/84/09e9d384f280e5540e6a6a6c09d736a064b5b03ce7512fef905cb70f8165/lxml-5.0.1-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
   ------------------------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\micha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [22]:
!cd yolov5 && python train.py --img 320 --batch 16 --epochs 500 --data dataset.yml --weights yolov5s.pt --workers 2


train: weights=yolov5s.pt, cfg=, data=dataset.yml, hyp=data\hyps\hyp.scratch-low.yaml, epochs=500, batch_size=16, imgsz=320, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=2, project=runs\train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github:  YOLOv5 is out of date by 3 commits. Use 'git pull' or 'git clone https://github.com/ultralytics/yolov5' to update.
fatal: cannot change to 'C:\Binus\Semester': No such file or directory
YOLOv5  2023-12-18 Python-3.11.7 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8

In [4]:
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/exp5/weights/last.pt', force_reload=True)


Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\micha/.cache\torch\hub\master.zip
YOLOv5  2024-1-7 Python-3.11.7 torch-2.1.2+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
Model summary: 157 layers, 7055974 parameters, 0 gradients, 15.9 GFLOPs
Adding AutoShape... 


In [ ]:
img = os.path.join('data', 'images', 'awake.3fd2faf8-9d8d-11ee-b135-e00af687c89b.jpg')

In [ ]:
results = model(img)
results.print()

In [ ]:
%matplotlib inline 
plt.imshow(np.squeeze(results.render()))
plt.show()

In [13]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Make detections 
    results = model(frame)
    
    cv2.imshow('YOLO', np.squeeze(results.render()))
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [6]:
if len(results.xywh[0]) > 0:
    dconf = results.xywh[0][0][4]
    dclass = results.xywh[0][0][5]

    if dconf.item() > 0.85 and dclass.item() == 1.0:
        filechoice = random.choice([1,2,3])



In [14]:
%pip install sounddevice
%pip install soundfile


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\micha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\micha\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [23]:
import cv2
import numpy as np
import sounddevice as sd
import soundfile as sf

cap = cv2.VideoCapture(0)


def play_alarm_sound():
    
    alarm_sound, _ = sf.read("C:\Binus\Semester 3\AI\MV27TES-alarm-[AudioTrimmer.com].mp3")
    sd.play(alarm_sound, samplerate=44100)

while cap.isOpened():
    ret, frame = cap.read()

    
    results = model(frame)
    print(results.xywh[0])
    if len(results.xywh[0]) > 0:
        if results.xywh[0][0][5] == 16.00:
            play_alarm_sound()
    

    cv2.imshow('YOLO', np.squeeze(results.render()))

    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


tensor([[347.57834, 265.23697, 289.65454, 298.51312,   0.62946,  16.00000]], device='cuda:0')
tensor([[340.98196, 261.30789, 284.54443, 275.51764,   0.74774,  16.00000]], device='cuda:0')
tensor([[324.18652, 264.74139, 280.85730, 276.32581,   0.55276,  16.00000]], device='cuda:0')
tensor([[322.41504, 269.50021, 299.66602, 301.73608,   0.47909,  16.00000]], device='cuda:0')
tensor([[321.33224, 270.20135, 324.00549, 329.78943,   0.35403,  16.00000]], device='cuda:0')
tensor([[3.36761e+02, 2.64800e+02, 3.95974e+02, 3.40727e+02, 3.51887e-01, 1.60000e+01]], device='cuda:0')
tensor([[3.37886e+02, 2.45948e+02, 3.81651e+02, 3.19807e+02, 3.43113e-01, 1.60000e+01]], device='cuda:0')
tensor([[366.75580, 263.26514, 347.95044, 331.10168,   0.42465,  16.00000]], device='cuda:0')
tensor([[370.67361, 261.85342, 333.51886, 330.07208,   0.48560,  16.00000]], device='cuda:0')
tensor([[359.99039, 262.68530, 370.00592, 317.58575,   0.41102,  16.00000]], device='cuda:0')
tensor([[3.48115e+02, 2.66017e+02, 3

In [ ]:
#if len(results.xywh[0]) > 0:
        #dconf = results.xywh[0][0][4]
        #dclass = results.xywh[0][0][5]
        
        #play_alarm_sound()


    # Assuming that 'drowsy' is one of the classes in your detection results
    #if dconf.item() > 0.80  and dclass.item() == 16.00:
        #play_alarm_sound()